### PR TITLE
Fix link to the Flight Manual and fix the picture in README.md

### PR DESCRIPTION
**Pull request by platy11**
I've updated the `README` to link to the Flight Manual in a better way, and fixed the 'Open Source' image.

### CODE REVIEW

**Comment by 50Wliu** [comment]
https://cloud.githubusercontent.com/assets/69169/7661190/60a6a044-fb05-11e4-8674-bf31d9f8b66f.jpg seems to link to a much higher-resolution picture.

**Comment by platy11** [comment]
@50Wliu okay, I'm now using that image instead.

**Comment by simurai** [comment]
🚢

**Comment by simurai** [comment]
Thinking about it. Maybe instead of the "open source" image we could show an actual screenshot of the site?. I'll make another PR for it.

**Pull request merged**
